include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Code quality
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true

    # Safety / bug prevention
    avoid_unnecessary_containers: true
    use_build_context_synchronously: true
    avoid_returning_null_for_future: true
    cancel_subscriptions: true
    close_sinks: true

    # Style consistency
    prefer_single_quotes: true
    sort_constructors_first: true
    sort_child_properties_last: true

    # Performance
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true

    # Clean architecture friendliness
    depend_on_referenced_packages: true
    avoid_relative_lib_imports: true
