// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwndTZguMrWpKIN2yzF-z4cHoOWa25EnQ',
    appId: '1:878968057195:web:ef28ef89073ad360d8f02e',
    messagingSenderId: '878968057195',
    projectId: 'studydrill-89742',
    authDomain: 'studydrill-89742.firebaseapp.com',
    storageBucket: 'studydrill-89742.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAhNPBDaWjUyULGjFilburNS4yPYU-bY0',
    appId: '1:878968057195:android:4592a4326824be7fd8f02e',
    messagingSenderId: '878968057195',
    projectId: 'studydrill-89742',
    storageBucket: 'studydrill-89742.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWxs-vpqJ1pBFE2hXWC9y7UeXcx6QNzh4',
    appId: '1:878968057195:ios:24a0cdb350216626d8f02e',
    messagingSenderId: '878968057195',
    projectId: 'studydrill-89742',
    storageBucket: 'studydrill-89742.firebasestorage.app',
    iosClientId: '878968057195-4necagc5rii6uaqf7olhikaucejki0pn.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyDrill',
  );
}
